### ISSUE TITLE
Use the new cache module in pytest

### ISSUE THREAD

**Issue by santagada** [tholo/pytest-flake8#1]
pytest now comes with cache as a default module and doesn't load the pytest-cache plugin anymore, by not using the default one pytest-flake8 is not caching results anymore

**Comment by santagada** [comment]
:+1: but using flake8 0.3 it still don't seem to use the internal caching module, every time I run tests with --flake8 it runs the checks everywhere

**Comment by tholo** [comment]
Actual skipping is still not happening...
