### ISSUE TITLE
Support flake8 v2

### ISSUE THREAD

**Issue by jayvdb** [tholo/pytest-flake8#10]
pytest supports py26, but flake8 v3 does not.

A nice way to handle this is for pytest-flake8 to support flake8 v2 while py26 is supported by pytest, or most pytest projects have had enough time to implement v3 without regressions (many flake8 plugins are broken in v3.)

**Comment by jayvdb** [comment]
see https://github.com/pypa/setuptools/pull/695 for a project stuck with needing py26 support

**Comment by tholo** [comment]
If you need to support py26 you'll need to stick to version 0.5, sorry.
