### ISSUE TITLE
Distribute via conda forge

### ISSUE THREAD

**Issue by kynan** [tholo/pytest-flake8#15]
Would you be interested to create a recipe for distributing pytest-flake8 via [conda forge](http://conda-forge.github.io)? Alternatively I could create one if you like.

**Comment by tholo** [comment]
I do not use conda -- but I'd be willing to entertain a pull request.

**Comment by kynan** [comment]
The recipe would actually be added to https://github.com/conda-forge/staged-recipes. I'll go ahead with that then.
