### ISSUE TITLE
ability to run flake8 before other tests

### ISSUE THREAD

**Issue by ssbarnea** [tholo/pytest-flake8#17]
I discovered that flake8 tests are executed after the unittest are executed which doesn't make much sense. The idea is that unittests do take a very long time to execute but linting is much faster.

You want to run linting before running the tests and eventually even stopping the execution right away if linting fails. 

I am not sure if this is a limitation of pytest but even if it is, it would should be sorted because without it we are better off using flake8 outside pytest. 

Many people, including myself, are also using tox and if pytest-flake8 is not able to run before the unittests, I would prefer to trigger flake8 before pytest from tox and not use `pytest-flake8` plugin.

**Comment by QuLogic** [comment]
I think this works the same way as `pytest-pep8` did; all flake8 tests are marked with `flake8`, so you can pick only them out using: `pytest --flake8 -m flake8`

**Comment by tholo** [comment]
The order in which to execute individual plugins is outside the control of the plugins themselves.
