### ISSUE TITLE
pytest-flake8 is incompatible with hacking module

### ISSUE THREAD

**Issue by ssbarnea** [tholo/pytest-flake8#18]
I realised that adding `pytest-flake8` to you project is incompatible with use of python [hacking](https://pypi.python.org/pypi/hacking/0.12.0) package due to the conflict regarding flake8 version.

    ... flake8-3.0.4-py3.5.egg), Requirement.parse('flake8<2.6.0,>=2.5.4'), {'hacking'})

For good reasons hacking package restricts python linting packages installed to safe ranges, so people would not be surprised by their CI gates going broken.

If `pytest-flake8` would allow a wider range of flake8 version we would not risk of having to implement ugly `requirements.txt` workarounds like:
```
hacking
pytest-flake8<0.6
flake8<2.6.0
```
The last two lines are needed only because if `pytest-flake8>=0.6` would also install `flake8>3.0`.

If you have a new `pip>=9.0` you can easily find conflicts using `pip check`.

**Comment by tholo** [comment]
There is not much we can do about that...
