### ISSUE TITLE
reconcile version numbers

### ISSUE THREAD

**Issue by ktdreyer** [tholo/pytest-flake8#3]
There are some discrepancies regarding version numbers of pytest-flake8.

* pytest_flake8.py's `__version__` says `0.2`
* CHANGELOG and setup.py say `0.3`
* pypi has `0.4`

After merging #2 , would you mind bumping to `0.5` (and pushing that to GitHub) in order to resolve this?

**Comment by tholo** [comment]
Fixed, thank you!

**Comment by ktdreyer** [comment]
Thank you!
