### ISSUE TITLE
Honor ignore in setup.cfg / tox.ini

### ISSUE THREAD

**Issue by brianbruggeman** [tholo/pytest-flake8#30]
Currently `pytest-flake8` will ignore/override the standard [flake8] ignore section even if flake8-ignore is not present within the [tool:pytest] section.  The default behavior should be to honor the settings in the [flake8] section within `setup.cfg` or `tox.ini`.

**Comment by tholo** [comment]
I think this was corrected in #21

**Comment by brianbruggeman** [comment]
Cool.  Thanks!  Is this in the latest release on Pypi (it looks like it was most recently updated in the last 24 hours)?

From a review standpoint, I would have probably added a test or two to validate.

**Comment by brianbruggeman** [comment]
Having tested the solution in #21 with a project I'm working on... I don't think it fixes the issue and I think it may break things.

I have an alternative fix here:   https://github.com/tholo/pytest-flake8/pull/31

**Comment by henning** [comment]
Having this issue too and I was about to file a bug.

Currently the only way to commonly ignore some kinds of errors (e.g. style problems in django-generated migrations) independent of  wether flake8 is run directly or via pytest is to annotate/comment in the files directly. 

I'd stringly prefer that I can configure all flake8 stuff in a pytest independent way so however flake8 is run later, it will be configured correctly.

**Comment by artiemq** [comment]
Fixed in #31
