### ISSUE TITLE
Transfer repository to pytest-dev organization.

### ISSUE THREAD

**Issue by lk-geimfari** [tholo/pytest-flake8#36]
As i can judge the current maintainer can't maintain this porject for some reasons. I suggest to transfer this repository to pytest-dev community. 

P.S Also it would be awesome to transfer PyPi package for publishing new version of this plugin.

**Comment by lk-geimfari** [comment]
It's because a lot of open source project depend this package for testing.

**Comment by tholo** [comment]
The current maintainer (and creator) has had ... some life events to deal with over the last year and has had (very!) limited time available. That looks to finally be changing somewhat...

**Comment by lk-geimfari** [comment]
I'm sorry, I thought you abandoned the project. Thanks for the feedback!

**Comment by jacquerie** [comment]
> The current maintainer (and creator) has had ... some life events to deal with over the last year and has had (very!) limited time available. That looks to finally be changing somewhat...

Thanks for all the work you've done so far on this plugin, and in particular for all the work you're doing right now to fix this latest problem with `flake8==3.5.0`. Rest assured that if you ever need again some time off from the project there's lots of people among its users that can help carry the weight :+1:
