### ISSUE TITLE
Support flake8's setup.cfg?

### ISSUE THREAD

**Issue by tony** [tholo/pytest-flake8#5]
flake8 supports ``[flake8]`` in setup.cfg, but when using pytest-flake8 0.5 with flake8 2.6.0, the flake8 isn't obeyed

http://flake8.readthedocs.io/en/latest/config.html

Any chance there could be support for parsing the project's setup.cfg?

**Comment by sastred** [comment]
Hi @tony,

It works for me with the following setup.cfg

```
[tool:pytest]
addopts = --flake8

[flake8]
;ignore = E501 E116
max-line-length = 120
max-complexity = 10
```

My requirements.txt:

```
pytest==3.0.1
pytest-flake8==0.6
pytest-sugar==0.7.1
pytest-xdist==1.15.0
```
