### ISSUE TITLE
No make_notifier with latest flake8

### ISSUE THREAD

**Issue by jaraco** [tholo/pytest-flake8#56]
I had a project that was pinned to [pycqa/flake8 master](92efb041d961ae4af0e5dcc0baadb0184258e1c1). When I ran the tests recently, they started failing with this error:

```
.tox/python/lib/python3.7/site-packages/pluggy/hooks.py:284: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
.tox/python/lib/python3.7/site-packages/pluggy/manager.py:68: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox/python/lib/python3.7/site-packages/pluggy/manager.py:62: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
.tox/python/lib/python3.7/site-packages/_pytest/runner.py:123: in pytest_runtest_call
    item.runtest()
.tox/python/lib/python3.7/site-packages/pytest_flake8.py:117: in runtest
    self.statistics)
.tox/python/lib/python3.7/site-packages/py/_io/capture.py:150: in call
    res = func(*args, **kwargs)
.tox/python/lib/python3.7/site-packages/pytest_flake8.py:190: in check_file
    app.make_notifier()
E   AttributeError: 'Application' object has no attribute 'make_notifier'
```

Removing the dependency on master and allowing the `pytest-flake8` dependency to designate flake8 corrected the issue.

But I wanted to report this issue here in case I've stumbled on a bug that might emerge with the next release of flake8. Feel free to investigate or close as you see fit.

**Comment by sambrightman** [comment]
This just hit us with flake8 3.7.1 (vs 3.6.0 working).

**Comment by jwegger** [comment]
Hit us too, seems to have changed in v3.7.0 which was released some hours ago. Release note says:
- Remove broken and unused flake8.listen plugin type (See also GitLab!274, GitLab#480)
https://gitlab.com/pycqa/flake8/merge_requests/274
