### ISSUE TITLE
All flake8 tests skipped

### ISSUE THREAD

**Issue by berislavlopac** [tholo/pytest-flake8#62]
I'm running the tests with a command like this:

```sh
pytest --flake8 src/database/tables.py
```
However, whatever I do, all `flake8` tests are skipped:

```
collected 1 item                                                                                                       

src/database/tables.py s                                                         [100%]
```

`flake8` works fine on its own. Any ideas where to look for the problem? Thanks!

**Comment by tholo** [comment]
This is by design -- things that came out clean are cached and unless modified, not tested again.

You can run with `pytest --cache-clear --flake8` to override this.

**Comment by berislavlopac** [comment]
Ah I see -- thank you!
