### ISSUE TITLE
ImportError: No module named 'flake8.engine'

### ISSUE THREAD

**Issue by jaraco** [tholo/pytest-flake8#7]
Running pytest-flake8 against the latest flake8 (3.0.0b2), it fails with the error in the title. It [appears that flake8 has moved the flake8.engine module](https://gitlab.com/pycqa/flake8/blob/master/src/flake8/api/legacy.py).

When using `easy_install` to install pytest-flake8, it doesn't protect against pre-releases, so the requirements on pytest-flake8 pick up the incompatible beta release. Perhaps pytest-flake8 should depend on `flake8>=2.5,<3dev` until compatibility code can be added for flake8 3.0 support.

**Comment by santagada** [comment]
Now flake8 3.0.0 has been released so pytest-flake8 is broken
