### ISSUE TITLE
FLAKE8 - NotImplementedError: abstract

### ISSUE THREAD

**Issue by sbv-csis** [tholo/pytest-flake8#72]
When running pytest with `-f` after a flake8 error is fixed you get:
```
ERROR test_something.py::FLAKE8 - NotImplementedError: abstract
```

It seems to be related to #71 maybe?

I've made an example here: https://gist.github.com/sbv-csis/8b693ce75c335921f0fbded7fa2df9b5

The basic idea is that you start `pytest -f` so it loops, and following flake8 problems it won't recover from 
``` 
ERROR test_something.py::FLAKE8 - NotImplementedError: abstract
```

**Comment by sbv-csis** [comment]
Just verified - #71 fixes this issue too

**Comment by jwegger** [comment]
Seing this too. I was able to temporarily work around it by using pytest<6.1.0. Not sure which change in 6.1.0 triggers it, the only slightly related change I could spot was https://github.com/pytest-dev/pytest/issues/7591.

**Comment by sbv-csis** [comment]
New version of pytest out now. This is still a issue it seems

**Comment by tholo** [comment]
New release has been published which should fix this
